# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2d63ea976ce7de2daef8a5b609f85ffeaedf4ced23f8a6498b6c1af880482d8f6c475c079e708fc9261241e5f2aa91ac9a5708194e09e11ce80339b2aaf8699f

test:
  secret_key_base: d070c7682b8bfd2b7eb5929f6e1abb68c1c2c3c43e75d7d2cdf6a3e14cf5dfd8704bd4d52b3cc77034cbf3b70168fc9088fb73f12e0b452fa83a09fd042bab0f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
